#pragma config(UART_Usage, UART1, uartUserControl, baudRate38400, IOPins, None, None)
#pragma config(Motor,  port2,           motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           motor5,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           motor6,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           motor7,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           motor8,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           motor9,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard   !!*//
#include "serialCortex_2.h"

task main()
{
	driverControl = false;

  StartTask(serialRxTask);

  while(1)
  {
  	wait1Msec(10);
  }
}
